Change behaviour of debian/bin/u-boot-install-* for an unknown device tree (Closes: #976315)
When unexpected contents are found in /sys/firmware/devicetree/base/model,

* debian/bin/u-boot-install-rockchip reports
  'ERROR: Unknown system: /sys/firmware/devicetree/base/model'.
  This is probably not the intention of the script author.

* debian/bin/u-boot-install-sunxi64 selects pine64_plus.
  An error would be safer than a risk of later boot failure.

Let both scripts report an error message including the unknown system
description instead.

Describe the TARGET environment variable in the manual page.

Adjusted-by: Vagrant Cascadian <vagrant@debian.org>

diff --git a/debian/bin/u-boot-install-rockchip b/debian/bin/u-boot-install-rockchip
--- a/debian/bin/u-boot-install-rockchip
+++ b/debian/bin/u-boot-install-rockchip
@@ -3,7 +3,8 @@ set -e
 
 dtmodel="/sys/firmware/devicetree/base/model"
 if [ -z "$TARGET" ] && [ -f "${dtmodel}" ]; then
-	case $(cat "${dtmodel}") in
+	dtmodelname=$(cat $dtmodel)
+	case "$dtmodelname" in
 		Firefly-RK3288)
 			TARGET="/usr/lib/u-boot/firefly-rk3288"
 			UBOOT_IMAGE="u-boot.img"
@@ -24,7 +25,7 @@ if [ -z "$TARGET" ] && [ -f "${dtmodel}" ]; then
 			TARGET="/usr/lib/u-boot/rock-pi-4-rk3399"
 			;;
 		*)
-			echo >&2 "ERROR: Unknown system: ${dtmodel}"
+			echo >&2 "ERROR: Unknown system: ${dtmodelname}"
 			echo >&2 "Specify target: TARGET=/usr/lib/u-boot/UBOOT"
 			exit 1
 			;;
diff --git a/debian/bin/u-boot-install-sunxi64 b/debian/bin/u-boot-install-sunxi64
--- a/debian/bin/u-boot-install-sunxi64
+++ b/debian/bin/u-boot-install-sunxi64
@@ -3,7 +3,8 @@ set -e
 
 dtmodel="/sys/firmware/devicetree/base/model"
 if [ -z "$TARGET" ] && [ -f "${dtmodel}" ]; then
-	case $(cat "${dtmodel}") in
+	dtmodelname=$(cat $dtmodel)
+	case "$dtmodelname" in
 		Pinebook) TARGET="/usr/lib/u-boot/pinebook" ;;
 		Pine64+) TARGET="/usr/lib/u-boot/pine64_plus" ;;
 		"Pine64 LTS") TARGET="/usr/lib/u-boot/pine64-lts" ;;
@@ -13,6 +14,11 @@ if [ -z "$TARGET" ] && [ -f "${dtmodel}" ]; then
 		"OrangePi Zero Plus2") TARGET="/usr/lib/u-boot/orangepi_zero_plus2/" ;;
 		"FriendlyARM NanoPi NEO 2") TARGET="/usr/lib/u-boot/nanopi_neo2/" ;;
 		"FriendlyARM NanoPi NEO Plus2") TARGET="/usr/lib/u-boot/nanopi_neo_plus2/" ;;
+		*)
+			echo >&2 "ERROR: Unknown system: ${dtmodelname}"
+			echo >&2 "Specify target: TARGET=/usr/lib/u-boot/UBOOT"
+			exit 1
+			;;
 	esac
 fi
 
@@ -21,7 +27,6 @@ if [ -z "$BL31" ] && [ -f "${atf}" ]; then
 	BL31="${atf}"
 fi
 
-TARGET=${TARGET:-"/usr/lib/u-boot/pine64_plus"}
 BL31=${BL31:-"/usr/lib/atf/sun50iw1p1/bl31.bin"}
 FIT_GENERATOR=${FIT_GENERATOR:-"mksunxi_fit_atf"}
 
