u-boot-sunxi: u-boot-install-sunxi64: Error out when mkimage is not found and Recommend u-boot-tools (Closes: #913879).  Thanks to Nicolas Schier.

diff --git a/debian/bin/u-boot-install-sunxi64 b/debian/bin/u-boot-install-sunxi64
--- a/debian/bin/u-boot-install-sunxi64
+++ b/debian/bin/u-boot-install-sunxi64
@@ -28,6 +28,11 @@ case "$1" in
 	exit 1;;
 esac
 
+if [ -z "$(which mkimage)" ]; then
+	echo >&2 "$0: mkimage: command not found. Please install u-boot-tools."
+	exit 1
+fi
+
 DEV="$1"
 if [ -z "$DEV" ] || ! shift || [ -n "$*" ]; then
     echo >&2 "Usage: $0 /dev/your-sd-or-mmc-or-image"
